# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths: [
      'resources/**',
      'admin/resources/**'
    ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    #run only if push into main production branch
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.author.name, 'github-actions[bot]') }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    name: production-build 🛠

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
      - name: Install dependencies
        run: npm install --non-interactive
      - name: Make production build
        run: npm run build
      - name: Commit production build
        uses: EndBug/add-and-commit@v7
        with:
          add: "public"
          push: "origin main --force"
          default_author: github_actions
          message: "Apply production build from CI

          Co-authored-by: aw-ci-bot <bot@aw-studio.de>"
